version: "3.8"

services:
  backend:
    build: ./server
    container_name: express-api
    networks:
      - nginx-net
    environment:
      - API_KEY=exampleAPIKEY
    restart: unless-stopped
  frontend:
    build: ./client
    container_name: react-app
    networks:
      - nginx-net
    depends_on:
      - backend
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - nginx-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/example_certs:/etc/nginx/certs

networks:
  nginx-net:
